### ISSUE TITLE
clean code

### ISSUE THREAD

**Issue by akbarjondev** [abdulatifkhan/pizza-delicious#2]
https://github.com/abdulatifkhan/pizza-delicious/blob/c18c35b4443d422e31d2b8dbca0ded575d1e5df0/js/scripts.js#L134

kodni iloji boricha keraksiz kodlardan tozalaymiz, bo'lmasa chalg'ishlarga sabab bo'ladi

**Comment by abdulatifkhan** [comment]
Rahmat! Maslahatlarga amal qilamiz!
